#define CLEAR_LCD            0x01
#define RET_CUR_HOME         0X02
#define SHIFT_CUR_RIGHT      0X06
#define SHIFT_CUR_LEFT       0X07
#define DISPLAY_OFF          0X08
#define DISPLAY_ON_CUR_OFF   0X0C
#define DISP_ON_CUR_ON       0X0E
#define SHIFT_DISP_RIGHT     0X14
#define SHIFT_DISP_LEFT      0X10
#define MODE_8BIT            0X30
#define SET_INTERFACE        0X38
#define SHIFT_DISP_RIGHT     0X14
#define GOTO_LINE1_POS0      0X80
#define GOTO_LINE2_POS0      0xC0
#define GOTO_CGRAM_START     0X40
#define LCD_data 0xff
#define RS 8
#define EN 9
#define RW 10
